if(CMAKE_Fortran_COMPILER_ID STREQUAL GCC)
  set(old -w -std=legacy)
elseif(CMAKE_Fortran_COMPILER_ID STREQUAL Intel)
  if(WIN32)
    set(old /nowarn)
  else()
    set(old -nowarn)
  endif()
elseif(CMAKE_Fortran_COMPILER_ID STREQUAL PGI)
  set(old -w)
elseif(CMAKE_Fortran_COMPILER_ID STREQUAL Flang)
  set(old -w)
endif()