name: ci

env:
  HOMEBREW_NO_INSTALL_CLEANUP: 1
  CTEST_NO_TESTS_ACTION: error
  CTEST_PARALLEL_LEVEL: 0
  CMAKE_BUILD_PARALLEL_LEVEL: 4

on:
  push:
    paths:
      - "**.f"
      - "**.f90"
      - "**/CMakeLists.txt"
      - "**.cmake"
      - ".github/workflows/ci.yml"
  workflow_dispatch:

# avoid wasted runs
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true


jobs:

  unix:
    strategy:
      matrix:
        shared: [true, false]
        os: [ubuntu-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    timeout-minutes: 15

    env:
      CMAKE_INSTALL_PREFIX: ~/libs

    steps:

    - uses: actions/checkout@v4

    - name: set FC on macOS
      if: runner.os == 'macOS'
      run: echo "FC=gfortran-14" >> $GITHUB_ENV

    - name: Configure
      run: >
        cmake --preset default
        -DBUILD_SHARED_LIBS:BOOL=${{ matrix.shared }}

    - name: Build and test
      run: cmake --workflow --preset default

    - name: Install
      run: cmake --install build

  windows:
    timeout-minutes: 15
    runs-on: windows-latest

        # shared always error 135 even on only shared. not a problem on real pc.

    steps:
    - uses: msys2/setup-msys2@v2
      id: msys2
      with:
        update: true
        install: >-
          mingw-w64-ucrt-x86_64-gcc-fortran

    - name: Put MSYS2_MinGW64 on PATH
      run: echo "${{ steps.msys2.outputs.msys2-location }}/ucrt64/bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

    - uses: actions/checkout@v4

    - name: Configure
      run: cmake --workflow --preset default
      env:
        CMAKE_GENERATOR: Ninja
