name: ci

env:
  CTEST_PARALLEL_LEVEL: 2
  CMAKE_BUILD_TYPE: Release

on:
  push:
    paths:
      - "**/*.f"
      - "**/*.f90"
      - "**/CMakeLists.txt"
      - "**.cmake"
      - ".github/workflows/ci.yml"

jobs:

  cmake:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            fc: gfortran
            cmake_gen: "Unix Makefiles"
          - os: macos-latest
            fc: gfortran-11
            cmake_gen: "Unix Makefiles"
          - os: windows-latest
            fc: gfortran
            cmake_gen: "MinGW Makefiles"

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2

    - run: cmake -B build
      env:
        CMAKE_GENERATOR: ${{ matrix.cmake_gen }}
        FC: ${{ matrix.fc }}

    - run: cmake --build build

    - run: ctest --test-dir build --preset default



  meson:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            fc: gfortran
          - os: macos-latest
            fc: gfortran-11
          - os: windows-latest
            fc: gfortran

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - run: pip install meson ninja

    - run: meson setup build
      env:
        FC: ${{ matrix.fc }}

    - run: meson compile -C build

    - run: meson test -C build -v
