name: ci

env:
  HOMEBREW_NO_INSTALL_CLEANUP: 1

on:
  push:
    paths:
      - "**.f"
      - "**.f90"
      - "**/CMakeLists.txt"
      - "**.cmake"
      - ".github/workflows/ci.yml"
  workflow_dispatch:

# avoid wasted runs
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true


jobs:

  unix:
    strategy:
      matrix:
        preset: [default, shared]
        platform: [
          { os: ubuntu-latest, fc: gfortran },
          { os: macos-latest, fc: gfortran-15 }
          ]

    env:
      FC: ${{ matrix.platform.fc }}

    runs-on: ${{ matrix.platform.os }}

    timeout-minutes: 15

    steps:

    - &checkout
      uses: actions/checkout@v7

    - name: Build and test
      run: cmake --workflow ${{ matrix.preset }}

    - name: Install
      run: cmake --install build

  windows:
    timeout-minutes: 15
    runs-on: windows-latest

    env:
      FC: gfortran

    steps:
    - *checkout

    - name: Configure
      run: cmake --workflow default
