name: ci

env:
  HOMEBREW_NO_INSTALL_CLEANUP: 1

on:
  push:
    paths:
      - "**.f"
      - "**.f90"
      - "**/CMakeLists.txt"
      - "**.cmake"
      - ".github/workflows/ci.yml"

jobs:

  cmake_unix:
    strategy:
      matrix:
        shared: [true, false]
        os: [ubuntu-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:

    - name: install gcc
      if: runner.os == 'macOS'
      run: brew reinstall gcc

    - uses: actions/checkout@v3

    - run: cmake -B build -DBUILD_SHARED_LIBS:BOOL=${{ matrix.shared }}
    - run: cmake --build build
    - run: ctest --test-dir build --preset default


  msys2:
    timeout-minutes: 20
    runs-on: windows-latest

    env:
      CMAKE_GENERATOR: MinGW Makefiles

    strategy:
      matrix:
        shared: [false]

    steps:
    - uses: msys2/setup-msys2@v2
      with:
        update: true
        install: >-
          mingw-w64-x86_64-gcc-fortran

    - name: Put MSYS2_MinGW64 on PATH
      run: echo "${{ runner.temp }}/msys64/mingw64/bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

    - uses: actions/checkout@v3

    - run: cmake -B build -DBUILD_SHARED_LIBS:BOOL=${{ matrix.shared }}
    - run: cmake --build build
    - run: ctest --test-dir build --preset default
