name: ci_linux

on:
  push:
    paths:
      - "**/*.f"
      - "**/*.f90"
      - "**/CMakeLists.txt"
      - "**.cmake"
      - ".github/workflows/ci_linux.yml"

jobs:

  cmake313:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Get CMake 3.13
      run: |
        curl -L -O https://github.com/Kitware/CMake/releases/download/v3.13.4/cmake-3.13.4-Linux-x86_64.tar.gz
        tar -xf cmake-3.13.4-Linux-x86_64.tar.gz
        echo "${GITHUB_WORKSPACE}/cmake-3.13.4-Linux-x86_64/bin" >> $GITHUB_PATH


    - run: cmake -B build
    - run: cmake --build build --parallel
    - run: ctest --output-on-failure
      working-directory: build


  meson:
    if: false  # not used currently, but should work
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - run: pip install meson ninja

    - run: meson setup build
    - run: meson compile -C build

    - run: meson test -C build -v
