name: ci_linux

env:
  CTEST_PARALLEL_LEVEL: 2
  CMAKE_BUILD_TYPE: Release

on:
  push:
    paths:
      - "**/*.f"
      - "**/*.f90"
      - "**/CMakeLists.txt"
      - "**.cmake"
      - ".github/workflows/ci_linux.yml"

jobs:

  cmake:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - run: cmake -B build
    - run: cmake --build build
    - run: ctest --test-dir build --preset default


  # meson:
  #  # not used currently, but should work
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/checkout@v2
  #   - uses: actions/setup-python@v2
  #     with:
  #       python-version: '3.x'

  #   - run: pip install meson ninja

  #   - run: meson setup build
  #   - run: meson compile -C build

  #   - run: meson test -C build -v
