name: ci_linux

on:
  push:
    paths:
      - "**/*.f"
      - "**/*.f90"
      - '**/*.txt'
      - '**/*.build'
      - ".github/workflows/ci_linux.yml"
  pull_request:
    paths:
      - "**/*.f"
      - "**/*.f90"
      - '**/*.txt'
      - '**/*.build'
      - ".github/workflows/ci_linux.yml"

jobs:

  cmake:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v1
      with:
        python-version: '3.x'

    - name: Install Prereqs
      run: |
        sudo apt update -yq
        sudo apt install -yq --no-install-recommends gfortran
    - run: pip install cmake

    - run: cmake -B build
      env:
        FC: gfortran
    - run: cmake --build build --parallel
    - uses: actions/upload-artifact@v1
      if: failure()
      with:
        name: Linux_Cmake_log
        path: build/CMakeFiles/CMakeError.log

    - run: ctest --parallel -V
      working-directory: build


  meson:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v1
      with:
        python-version: '3.x'
    - run: pip install -r requirements.txt
    - name: Install Prereqs
      run: |
        sudo apt update -yq
        sudo apt install -yq --no-install-recommends gfortran

    - run: meson setup build
      env:
        FC: gfortran
    - run: ninja -C build
    - uses: actions/upload-artifact@v1
      if: failure()
      with:
        name: Linux_Meson_Buildlog
        path: build/meson-logs/meson-log.txt

    - run: meson test -C build -v
    - uses: actions/upload-artifact@v1
      if: failure()
      with:
        name: Linux_Meson_Testlog
        path: build/meson-logs/testlog.txt
