name: ci_macos

on:
  push:
    paths:
      - "**/CMakeLists.txt"
      - "**.cmake"
      - ".github/workflows/ci_macos.yml"


jobs:

  cmake:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2

    - run: cmake -B build
      env:
        FC: gfortran-10
    - run: cmake --build build
    - run: ctest --output-on-failure
      working-directory: build


  meson:
    if: false  # not used currently, but should work
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - run: pip install meson ninja

    - run: meson setup build
    - run: meson compile -C build

    - run: meson test -C build -v
