name: ci_macos

on:
  push:
    paths:
      - "**/*.f"
      - "**/*.f90"
      - '**/*.txt'
      - '**/*.build'
      - ".github/workflows/ci_macos.yml"


jobs:

  cmake:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2

    - run: brew install gcc

    - run: ctest -S setup.cmake -VV


  meson:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - run: pip install meson
    - run: brew install gcc ninja

    - run: meson setup build

    - run: meson compile -C build
    - uses: actions/upload-artifact@v1
      if: failure()
      with:
        name: MacOS_Meson_Buildlog
        path: build/meson-logs/meson-log.txt

    - run: meson test -C build -v
    - uses: actions/upload-artifact@v1
      if: failure()
      with:
        name: MacOS_Meson_Testlog
        path: build/meson-logs/testlog.txt
